MBTN_RIGHT  script-binding select/context-menu

# ===== play =====
Space       cycle pause
PLAYPAUSE   cycle pause
Ctrl+v      loadfile ${clipboard/text} ; show-text '+ ${clipboard/text}'
Ctrl+V      loadfile ${clipboard/text} ; show-text '+ ${clipboard/text}'
l           script-binding select/select-playlist
L           script-binding select/select-playlist
NEXT        playlist-next
PREV        playlist-prev

# ===== seek =====
Right       seek  10
Left        seek -10
Ctrl+Right  seek  600
Ctrl+Left   seek -600

# ===== audio =====
WHEEL_UP    add volume  2
WHEEL_DOWN  add volume -2
m           cycle mute
M           cycle mute

# ===== misc =====
t       script-binding stats/display-stats-toggle
T       script-binding stats/display-stats-toggle
`       script-binding console/enable
·       script-binding console/enable

# ===== fullscreen & window =====
ESC             set fullscreen no
Enter           cycle fullscreen
MBTN_LEFT_DBL   cycle fullscreen
Ctrl+t          cycle ontop
Ctrl+T          cycle ontop

# ===== custom =====
Alt+1  change-list glsl-shaders toggle "~~/shaders/ArtCNN_C4F32_DS.glsl"; show-text "Toggle shader ArtCNN_C4F32_DS"
Alt+2  change-list glsl-shaders toggle "~~/shaders/Ani4Kv2_ArtCNN_C4F32_i2_CMP.glsl"; show-text "Toggle shader Ani4Kv2_ArtCNN_C4F32_CMP"
Alt+3  change-list glsl-shaders toggle "~~/shaders/AniSD_ArtCNN_C4F32_i4_CMP.glsl"; show-text "Toggle shader AniSD_ArtCNN_C4F32_CMP"
Alt+4  vf toggle @frc-input,@frc; show-text "Toggle FRC"

# ===== quit =====
Q       quit
q       quit
