### basic ###
profile=high-quality
gpu-api=vulkan
hwdec=vulkan

### player ###
border=no
snap-window=yes
keep-open=yes
input-builtin-bindings=no
force-window=immediate
autocreate-playlist=same
directory-mode=ignore

## cache ###
icc-cache-dir=yes
icc-cache-dir=~~/_cache/icc
gpu-shader-cache=yes
gpu-shader-cache-dir=~~/_cache/shader

## watch-later ###
save-position-on-quit=yes
watch-later-options=start,aid,vid,sid
watch-later-dir=~~/_watch_later

## screenshot ###
screenshot-format=jxl
screenshot-jxl-distance=0.1
screenshot-dir=~~/_screenshot

### subtitles ###
blend-subtitles=video
sub-auto=fuzzy
sub-auto-exts=ass,srt,txt
sub-file-paths=subs

### languages ###
alang=ja,jpn,en,eng,ko,kor,wuu,zh,zho,chi
slang=zh-CN,zh,chi,zho,en,eng

### script-opts ###
script-opts=osc-layout=floating,osc-title=${filename},osc-windowcontrols=no,stats-font_size=15,console-font_size=15

[ytdl-cookies]
profile-cond=(path:match("^https?://") ~= nil) and (path:match("%.m3u8$") == nil)
profile-restore=copy
ytdl-raw-options-append=cookies=~/.config/mpv/cookies.txt

[fruc-vulkan]
profile-cond=platform == "windows" and container_fps > 0 and container_fps < 60 and height <= 1080
profile-restore=copy
vf-append=@frc:fruc_vulkan=fps=[source_fps*3]:perf=slow

[fruc-vulkan-2160p]
profile-cond=platform == "windows" and container_fps > 0 and container_fps < 60 and height > 1080
profile-restore=copy
vf-append=@frc:fruc_vulkan=fps=[source_fps*2]:perf=fast
